IntelligentNetworkSolutions/IllegalDumpSiteDetectionAndLandfillMonitoring

Dal/ApplicationSettingsDa.cs
Dal/ApplicationStorage/ApplicationDbContextFactory.cs
Dal/AuditLogsDa.cs
Dal/Helpers/ApplicationSettingsHelper.cs
Dal/IntranetPortalUsersTokenDa.cs
MailSend/MailService.cs
MainApp/Areas/IntranetPortal/Controllers/UserManagementController.cs
MainApp/Areas/IntranetPortal/Views/UserManagement/CreateUser.cshtml
MainApp/Helpers/ModulesAndAuthClaimsHelper.cs
MainApp/Program.cs
MainApp/appsettings.Development.json
MainApp/appsettings.json
SD/CodeSnippets/FactTest.snippet
SD/Helpers/ClaimsPrincipalExtensions.cs
SD/SD.csproj
Services/Interfaces/ILayoutService.cs
Services/Interfaces/Repositories/IApplicationSettingsDa.cs
Services/LayoutService.cs
Tests/ServicesTests/LayoutServiceTests.cs

feat: todo suggestions

---

docs/docfx_project/about/code_of_conduct.md
docs/docfx_project/about/intro.md
docs/docfx_project/about/project-charter.md
docs/docfx_project/development/think-licensing.md
docs/docfx_project/development/usefull-links.md
docs/docfx_project/index.md
docs/docfx_project/toc.yml

Project charter
Code of conduct

add documentation in about

---

.gitignore
MainApp.MVC/.npmrc
MainApp.MVC/Areas/Common/Views/Shared/_LayoutPage.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Layout.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_LayoutPage.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_ValidationScriptsPartial.cshtml
MainApp.MVC/Areas/PublicPortal/Views/Shared/_Layout.cshtml
MainApp.MVC/Areas/PublicPortal/Views/Shared/_ValidationScriptsPartial.cshtml
MainApp.MVC/Views/Shared/_Layout.cshtml
MainApp.MVC/Views/Shared/_ValidationScriptsPartial.cshtml
MainApp.MVC/appsettings.Development.json
MainApp.MVC/appsettings.json
MainApp.MVC/node-post-install.js
MainApp.MVC/package-lock.json
MainApp.MVC/package.json
MainApp.MVC/vendor.json
package-lock.json

23 add packagesjson and setup npm scripts for js libraries

---

.github/workflows/deploy_selfhosted.yml

ensure postinstall in deploy_selfhosted.yml

---

MainApp.BL/Services/DatasetServices/DatasetService.cs
MainApp.BL/Services/LegalLandfillManagementServices/LegalLandfillPointCloudFileService.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/LegalLandfillsManagementController.cs
MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsManagement/ViewPointCloudFiles.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
MainApp.MVC/Filters/HangfireDashboardAuthorizationFilter.cs
MainApp.MVC/Infrastructure/Configure/ConfigureHangfire.cs
MainApp.MVC/Infrastructure/Register/RegisterHangfire.cs
MainApp.MVC/MainApp.MVC.csproj
MainApp.MVC/Program.cs

feat: hangfire configuration

---

DAL/ApplicationStorage/ApplicationDbContext.cs
DAL/EnitityConfigurations/TrainingEntities/TrainingRunTrainParamsConfiguration.cs
DAL/Migrations/20240930234114_AddTrainRunConfigPathAndParamsTbl.Designer.cs
DAL/Migrations/20240930234114_AddTrainRunConfigPathAndParamsTbl.cs
Dal/EnitityConfigurations/TrainingEntities/TrainedModelStatisticsConfiguration.cs
Dal/EnitityConfigurations/TrainingEntities/TrainingRunConfiguration.cs
Entities/TrainingEntities/TrainedModel.cs
Entities/TrainingEntities/TrainingRun.cs
Entities/TrainingEntities/TrainingRunTrainParams.cs
MainApp.BL/Services/TrainingServices/TrainingRunService.cs

add TrainingRunTrainParams Table and Entity with configurations and a relationship to TrainingRun, where a Run can have one or zero TrainParams

feat: add TrainingRunTrainParams Table and Entity

---

Tests/MainAppBLTests/Services/MapLayerGroupConfigurationServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionIgnoreZonesControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/MapConfigurationControllerTests.cs
Tests/MainAppMVCTests/ViewModels/LegalLandfillManagementTests/LegalLandfillWasteImportViewModelTests.cs

fix: fixing bugs in some unit tests

---

.gitignore
MainApp.BL/Interfaces/Services/DatasetServices/IDatasetService.cs
MainApp.BL/Services/DatasetServices/DatasetService.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetsController.cs
MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Edit.cshtml

Funcionalities for exporting dataset as split dataset in separate folder's with their own json file

Dataset for split dataset

---

DTOs/MainApp.BL/DetectionDTOs/DetectedDumpSiteDTO.cs
MainApp.BL/Services/ApplicationSettingsService.cs
MainApp.BL/Services/DetectionServices/DetectionRunService.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
MainApp.MVC/appsettings.Development.json
MainApp.MVC/appsettings.Production.json
MainApp.MVC/appsettings.Staging.json
MainApp.MVC/appsettings.json
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs

fix: detection runs openmmlab path and hasGPU, appsettings update

feat: detections in ignore zones

---

DAL/EnitityConfigurations/DetectionEntities/DetectionRunConfiguration.cs
DAL/Migrations/20241016230406_AddTrainedModelToDetectionRun.Designer.cs
DAL/Migrations/20241016230406_AddTrainedModelToDetectionRun.cs
DTOs/Helpers/NewtonsoftJsonHelper.cs
DTOs/MainApp.BL/DetectionDTOs/DetectionRunDTO.cs
DTOs/ObjectDetection.API/CocoFormatDTOs/CocoAnnotationDTO.cs
DTOs/ObjectDetection.API/CocoFormatDTOs/CocoCategoryDTO.cs
Entities/DetectionEntities/DetectionRun.cs
MainApp.BL/Interfaces/Services/IMMDetectionConfigurationService.cs
MainApp.BL/Interfaces/Services/TrainingServices/ITrainedModelService.cs
MainApp.BL/Interfaces/Services/TrainingServices/ITrainingRunService.cs
MainApp.BL/Services/DatasetServices/DatasetService.cs
MainApp.BL/Services/DetectionServices/DetectionRunService.cs
MainApp.BL/Services/MMDetectionConfigurationsService.cs
MainApp.BL/Services/TrainingServices/TrainedModelService.cs
MainApp.BL/Services/TrainingServices/TrainingConfigGenerator.cs
MainApp.BL/Services/TrainingServices/TrainingRunService.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/TrainingRunsController.cs
MainApp.MVC/Infrastructure/Register/ApplicationServicesDependencyContainer.cs
SD/Helpers/CommonHelper.cs
Tests/MainAppBLTests/Services/DetectionRunServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs

feat: detection run uses trained model instead of hard coded

fix: training gives mAP: 0

---

MainApp.BL/Interfaces/Services/DatasetServices/IDatasetService.cs
MainApp.BL/Services/DatasetServices/DatasetService.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetsController.cs
MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Edit.cshtml

Added functionality to enable all of the image in a dataset

Functionality to enable all images of a dataset

---

MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
MainApp.MVC/Infrastructure/Register/InfrastructeServicesDependencyContainer.cs
Tests/DTOsTests/Helpers/GeoJsonHelpersTests.cs
Tests/DalTests/Repositories/UserManagementDaTests.cs
Tests/DalTests/SeedDbClasses/UserSeedData.cs
Tests/EntitiesTests/Helpers/GeoJsonHelpersTests.cs
Tests/Fixtures/TestDatabaseFixture.cs
Tests/MainAppBLTests/UserManagementServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/AccountControllerTests.cs

Added DAL Integration tests for User Managment, and Unit tests for Account controller, only the ones with sending email are left.

User management dal integration tests

---

MainApp.BL/Services/ImageAnnotationsService.cs
Tests/MainAppBLTests/Services/DatasetClassesServiceTests.cs
Tests/MainAppBLTests/Services/DatasetImagesServiceTests.cs
Tests/MainAppBLTests/Services/ImageAnnotationsServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/UserManagementControllerTests.cs
Tests/MainAppMVCTests/Helpers/LocalizationQueryProviderTests.cs
Tests/MainAppMVCTests/Helpers/ModulesAndAuthClaimsHelperTests.cs
Tests/MainAppMVCTests/Helpers/PasswordValidationHelperTests.cs

Dataset small missing unit tests

---

Tests/MainAppBLTests/Services/LegalLandfillPointCloudFileServiceTests.cs
Tests/MainAppBLTests/Services/TrainingServices/TrainedModelServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/ScheduleRunsControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/SpecialActionsControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/UserManagementControllerTests.cs

More unit tests forgot to change branch :)

Test dataset small missing

---

Tests/MainAppBLTests/Services/LegalLandfillServiceTests.cs
Tests/MainAppBLTests/Services/LegalLandfillTruckServiceTests.cs
Tests/MainAppBLTests/Services/LegalLandfillWasteImportServiceTests.cs
Tests/MainAppBLTests/Services/LegalLandfillWasteTypeServiceTests.cs
Tests/MainAppBLTests/UserManagementServiceTests.cs

Added LegalLandfillWaste service unit tests

LegalLandfillWaste unit tests

---

Tests/MainAppBLTests/Services/DetectionRunServiceTests.cs
Tests/MainAppBLTests/Services/MapLayerConfigurationServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/LegalLandfillWasteManagementControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/MapConfigurationControllerTests.cs

Added multiple unit tests for detection run service

Detection Run Service unit tests

---

Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/AuditLogsControllerTests.cs

Added auid log controller tests

Audit log controller tests

---

Tests/DTOsTests/MainAppBL/DatasetDTOsTests/ImageAnnotationDTOTests.cs
Tests/DTOsTests/MainAppBL/DetectionDTOsTests/DetectionRunJsonPayloadDTOTests.cs
Tests/DTOsTests/MainAppBL/DetectionDTOsTests/GroupedDumpSitesListHistoricDataDTOTests.cs
Tests/DTOsTests/MainAppBL/StringBuilderResultDTOTests.cs
Tests/DTOsTests/MainAppBL/TraninigDTOsTests/TrainingEpochMetricsDTOTests.cs
Tests/DTOsTests/MainAppBL/TraninigDTOsTests/TrainingEpochStepMetricsDTOTests.cs
Tests/DTOsTests/MainAppBL/TraninigDTOsTests/TrainingRunTrainParamsDTOTests.cs
Tests/MainAppMVCTests/ViewModels/AccountTests/IntranetUsersForgotPasswordViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/AccountTests/IntranetUsersResetPasswordViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/AccountTests/LoginViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/AccountTests/MyProfileViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/AuditLogTests/AuditLogListViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/AuditLogTests/AuditLogUserViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/AuditLogTests/AuditLogViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/ErrorTests/ErrorViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/LegalLandfillManagementTests/LegalLandfillWasteImportViewModelTests.cs
Tests/MainAppMVCTests/ViewModels/LegalLandfillManagementTests/PreviewViewModelTests.cs

Added missing tests for dtos and view models

Added missing tests for dtos and view models

---

Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/ScheduleRunsControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/UserManagementControllerTests.cs

Added unit tests for EditRole method.

UserManagementController unit tests

---

docs/docfx_project/documentation/toc.yml
docs/docfx_project/guides/toc.yml
docs/docfx_project/toc.yml

Docs revamp

---

Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/ApplicationSettingsControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DatasetImagesControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionIgnoreZonesControllerTests.cs

Detection Ignore Zones and AppSettings controller tests

Detection Ignore Zones and AppSettings controller tests

---

MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsWasteManagement/ViewLegalLandfillWasteImports.cshtml

Fixed the overflow of the datatable on the LegalLandfillWasteImports index view.

Fix: table overflowing on view LegalLandfillWasteImports

---

MainApp.MVC/Areas/IntranetPortal/Views/Annotations/Annotate.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/ApplicationSettings/Index.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/DatasetClasses/Index.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Index.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Detection/DetectedZones.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Detection/ViewAllImages.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsManagement/ViewLegalLandfills.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsManagement/ViewPointCloudFiles.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsWasteManagement/ViewLegalLandfillTrucks.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsWasteManagement/ViewLegalLandfillWasteImports.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsWasteManagement/ViewLegalLandfillWasteTypes.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/MapConfiguration/Index.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/MapConfiguration/_groupConfigurations.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/MapConfiguration/_layerConfigurations.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/ScheduleRuns/ViewScheduledRuns.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Layout.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_LayoutPage.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/TrainedModels/Index.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/TrainingRuns/Index.cshtml
MainApp.MVC/Areas/PublicPortal/Views/Shared/_Layout.cshtml
MainApp.MVC/Views/Shared/_Layout.cshtml
MainApp.MVC/package-lock.json
MainApp.MVC/package.json
MainApp.MVC/vendor.json
MainApp.MVC/wwwroot/css/site.css
package-lock.json
package.json

Sidebar changes and changes for all datatables responsivness.

Sidebar changes and datatables responsivness changes

---

MainApp.BL/Services/LegalLandfillManagementServices/LegalLandfillWasteTypeService.cs
MainApp.BL/Services/TrainingServices/TrainedModelService.cs
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsManagement/Preview.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsWasteManagement/ViewLegalLandfillTrucks.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
Tests/MainAppBLTests/Services/LegalLandfillWasteTypeServiceTests.cs

Custom error when waste type is used in waste imports on delete.
Sidebar menu changed to be collapsed on opening point clouds.
Changing some order in the Sidebar menu Datasets part.

Custom errors on delete

---

MainApp.MVC/Areas/IntranetPortal/Views/DatasetClasses/Index.cshtml

Fixed: Select2 dropdown still showing after closing modal.

bugfix: select2 dropdown on DatasetClasses

---

DTOs/MainApp.BL/MailSettingsDTO.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/LandingPageController.cs
MainApp.MVC/Areas/IntranetPortal/Views/Detection/DetectionInputImages.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LandingPage/Index.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
MainApp.MVC/wwwroot/css/LandingPage/landingPageStyle.css
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/LandingPageControllerTests.cs

Fixed multiple issues in this commit:
Functional contact form #140 ( needs to be tested )
Suggestions for the design of the landing page #141
Make the active sidebar menu group and item "active" #139

Fix: multiple issues on git

---

MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Index.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
MainApp.MVC/Views/Shared/Components/DetectionIgnoreZonesTool/Default.cshtml
MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml

Map - Detection Ignore zones tool - Description text issue Dataset buttons UI improvement
Area Comparison Avg Confidence Rate Modal not showing

fix: Create Detection Run - Issue during filling out the form

---

MainApp.MVC/Areas/IntranetPortal/Views/Account/MyProfile.cshtml
MainApp.MVC/Areas/IntranetPortal/Views/LegalLandfillsWasteManagement/CreateLegalLandfillWasteImport.cshtml

QA - Changes in the text fields for:
My profile - change password
Legallandfill waste imports - form ui changes

Fix: reset password form , waste import form ui changes

---

DTOs/ObjectDetection.API/MMDetectionConfiguration.cs
MainApp.BL/Interfaces/Services/IMMDetectionConfigurationService.cs
MainApp.BL/Services/DetectionServices/DetectionRunService.cs
MainApp.BL/Services/MMDetectionConfigurationsService.cs
MainApp.MVC/appsettings.Development.json
MainApp.MVC/appsettings.Production.json
MainApp.MVC/appsettings.Staging.json
MainApp.MVC/appsettings.json
Tests/DalTests/Repositories/MapConfigurationRepositories/MapConfigurationRepositoryTests.cs
Tests/DalTests/Repositories/UserManagementDaTests.cs
Tests/MainAppBLTests/Services/DetectionRunServiceTests.cs

refactor: removing dummy dataset class id,  setting hasGPU, appsettings json changes, adding missing mapping null check

fix: x unit tests fixinig

---

.gitignore
Tests/MainAppBLTests/Services/DatasetClassesServiceTests.cs
Tests/MainAppBLTests/Services/DatasetImagesServiceTests.cs
Tests/MainAppBLTests/Services/DatasetServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/AnnotationsControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DatasetClassesControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DatasetImagesControllerTests.cs

Updated unit tests after refactoring

Unit tests for Dataset services and controllers

---

MainApp.BL/Services/ApplicationSettingsService.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/ApplicationSettingsController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/AuditLogsController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionIgnoreZonesController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/LegalLandfillsManagementController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/LegalLandfillsWasteManagementController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/MapConfigurationController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/ScheduleRunsController.cs
MainApp.MVC/Areas/IntranetPortal/Controllers/TrainedModelsController.cs
MainApp.MVC/appsettings.Development.json
MainApp.MVC/appsettings.Production.json
MainApp.MVC/appsettings.Staging.json
MainApp.MVC/appsettings.json
SD/AuthClaims.cs
SD/Modules.cs
Tests/MainAppBLTests/Services/ApplicationSettingsServiceTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/ApplicationSettingsControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/AuditLogsControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/LegalLandfillsManagementControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/MapConfigurationControllerTests.cs
Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainedModelsControllerTests.cs
Tests/SDTests/Classes/ModulesTests.cs

feat: missing module appication settings added and also auth claims for that module
fix: fixed update application settings mapping failed, fixed x unit tests

refactor: try catch blocks added in controllers
